In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# 디렉토리 변경
cd '/content/drive/MyDrive/Numpy_and_Pandas/Numpy'

/content/drive/MyDrive/Numpy_and_Pandas/Numpy


In [10]:
# 1.넘파이 임포트
import numpy as np

In [13]:
# 2. ndarray객체 변환
data = [1,2,3]
data_numpy = np.array(data)

array([1, 2, 3])

In [14]:
# 3. 0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요.
data = np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
# 4. 구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요.
data = np.arange(1,10) * 3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# 5. 1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요.
data = np.arange(2,1000,2)

In [22]:
# 6. 0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.
data = np.arange(0,1,0.1)

In [24]:
# 7.reshape
data = [0, 1, 2, 3, 4, 5]
data = np.array(data)
data.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# 8. 다음의 2차원 ndarray 1차원 ndarray로 변환하세요.
arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

arr.reshape(-1)

array([0, 1, 2, 3, 4, 5])

In [27]:
# 9. 주어진 ndarray를 다음과 같이 변경해 보세요.
arr = np.arange(3)
arr.reshape(3,1)

array([[0],
       [1],
       [2]])

In [28]:
# 11. 2차원 ndarray 객체 정의
data = [
    [0, 1, 2],
    [3, 4, 5]
]
arr = np.array(data)

In [30]:
# 12. 1이 20개 저장된 아래의 ndarray 객체를 만들어 보세요.
np.ones(20,dtype='int64')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
# 13.4행 5열로 저장된 아래의 ndarray 객체를 만들어 보세요.(모든 원소의 값이 1인 경우)
np.ones([4,5],dtype='int64')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [36]:
# 14. 255로 채워진 10X10 크기의 ndarray 객체를 생성하세요.
np.ones([10,10],dtype='int64') * 255

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

In [38]:
# 15. 3x4 (행x열) 크기의 0으로 채워진 배열을 생생해보세요.
np.zeros([3,4],dtype='int64')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [39]:
# 16. [1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.
data = [1,2,3]
np.array(data,dtype='int32')

array([1, 2, 3], dtype=int32)

In [40]:
# 19.다음 데이터를 np.int16 타입의 배열로 형변환하세요.
arr = np.array([1, 2, 3])
np.asarray(arr,dtype='int16')

array([1, 2, 3], dtype=int16)

In [42]:
# 22. 0~10 사이를 구간을 20개의 포인트로 분할한 결과를 ndarray로 표현하라.
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [45]:
# 23. 다음의 ndarry 객체에서 마지막 로우([6, 7, 8])을 출력하세요.
arr = np.arange(9).reshape(3, 3)
arr[2]

array([6, 7, 8])

In [51]:
# 24. 다음의 ndarry 객체에서 두 번째 컬럼([1, 4, 7])을 출력하세요.
arr = np.arange(9).reshape(3, 3)
arr[:,1]

array([1, 4, 7])

In [52]:
# 25. 다음의 ndarray 객체에서 17을 선택하는 코드를 작성하라.
arr = np.arange(25).reshape(5, 5)
arr[3,2]

17

In [56]:
# 26. [1 3]을 슬라이싱 하는 코드를 작성하세요.
arr = np.arange(5)
arr[[1,3]]

array([1, 3])

In [57]:
# 27. [6 7 8 9]를 슬라이싱 하는 코드를 작성하세요.
arr = np.arange(25).reshape(5, 5)
arr[1,1:]

array([6, 7, 8, 9])

In [59]:
# 28. 첫번째와 두번째 컬럼을 슬라이싱하는 코드를 작성하세요.
arr = np.arange(25).reshape(5, 5)
arr[:,:2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [60]:
# 29. 6. 7,11, 12 를 2x2 ndarray로 슬라이싱하는 코드를 작성하세요.
arr = np.arange(25).reshape(5, 5)
arr[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [68]:
# 31. 전체 데이터에 10을 곱한 결과를 ndarray에 저장하세요
data = [1, 2, 3]
data = np.array(data) * 10
data

array([10, 20, 30])

In [69]:
# 32. 전체 데이터에 제곱한 결과를 ndarray에 저장하세요.
data = [1, 2, 3]
data = np.array(data) **2
data

array([1, 4, 9])

In [71]:
# 33. 전체 데이터에 루트를 적용한 결과를 ndarray에 저장하세요.
data = [1, 2, 3]
data = np.array(data) ** 0.5
data

array([1.        , 1.41421356, 1.73205081])

In [75]:
# 34. 과목별 평균 점수를 출력하세요.
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.mean(axis=0)

array([12., 18.])

In [77]:
# 35. 중간고사와 기말고사의 표준편차를 출력하세요.
score = np.array([
    [10, 20],  # 중간고사
    [14, 16]   # 기말고사
])
score.std(axis=1)

array([5., 1.])

In [79]:
# 36.두 행렬의 곱셉결과를 출력하세요.
a = np.arange(   4).reshape(2,2)
b = np.arange(1, 5).reshape(2,2)
np.dot(a,b)

array([[ 3,  4],
       [11, 16]])

In [80]:
# 37. 다음의 ndarray로 행과 열의 위치를 바꾼 전치행렬을 출력하세요.
arr = np.arange(9).reshape(3, 3)
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [88]:
# 38. 다음 배열에서 짝수 값만 추출하세요.
arr = np.arange(10)
arr[(arr%2==0) & (arr!=0)]

array([2, 4, 6, 8])

In [90]:
# 39. 다음 배열에서 홀수 값만 추출하세요.
arr = np.arange(10)
arr[(arr%2==1)]

array([1, 3, 5, 7, 9])

In [93]:
# 40. 다음 배열에서 3보다 크고 7보다 작은수만 추출하세요
arr = np.arange(10)
arr[(arr>3) & (arr<7)]

array([4, 5, 6])

In [94]:
# 41. 다음 ndarray 객체에서 음수를 출력하세요.
arr = np.array([-1, 2, -3, 4])
arr[arr<0]

array([-1, -3])

In [99]:
# 42. 다음 ndarray 객체에서 음수를 0으로 치환하세요
arr = np.array([-1, 2, -3, 4])
arr[arr<0] = 0
arr

array([0, 2, 0, 4])

In [98]:
# 43. 다음 ndarray 객체에서 음수를 양수로 변환하세요
arr = np.array([-1, 2, -3, 4])
arr[arr<0] = -arr[arr<0]
arr

array([1, 2, 3, 4])

In [100]:
# 44. 다음 ndarray 객체에서 양수 혹은 0이면 10을 더하고 음수는 10을 빼세요.
arr = np.array([-1, 2, -3, 4])
arr[arr>=0] = arr[arr>=0] + 10
arr[arr<0] = arr[arr<0] - 10
arr

array([-11,  12, -13,  14])

In [102]:
# 45. numpy random 모듈의 shuffle 함수를 사용해서 입력 리스트의 원소들을 랜덤하게 섞어 보세요.
arr = [1, 2, 3, 4, 5]
np.random.shuffle(arr)

In [103]:
# 46. 다음 넘파일 배열에서 최솟값의 인덱스를 출력하세요.
arr = np.array([1, 2, 3, 4, 5])
np.argmin(arr)

0

In [104]:
# 47.다음 넘파일 배열에서 최댓값의 인덱스를 출력하세요.
arr = np.array([1, 2, 3, 4, 5])
np.argmax(arr)

4

In [105]:
# 48.다음 넘파이 배열을 오름차순 정렬해보세요.
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [108]:
# 49. numpy.vstack 함수를 사용하여 다음 2차원 배열을 생성하세요.
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])

np.vstack([arr1,arr2]) # 행 쌓기
np.hstack([arr1,arr2]) # 열 쌓기

array([1, 2, 3, 4])

In [109]:
# 50. flatten 메서드를 사용하여 다음 배열을 1차원 배열로 변경하세요.
arr = np.array([ [1, 2], [3, 4] ])
np.flatten(arr)

AttributeError: module 'numpy' has no attribute 'flatten'

In [19]:
# 폴더 add
!git add Numpy.ipynb

In [20]:
# 커밋하기
!git commit -m 'Lets go 1st'
!git push

[main 26d2f05] Lets go 1st
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite Numpy.ipynb (60%)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 1.20 KiB | 102.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/NUMCHCOMCH/Numpy.git
   c7085c3..26d2f05  main -> main
