In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# 디렉토리 변경
cd '/content/drive/MyDrive/Numpy_and_Pandas/Numpy'

/content/drive/MyDrive/Numpy_and_Pandas/Numpy


In [10]:
# 1.넘파이 임포트
import numpy as np

In [13]:
# 2. ndarray객체 변환
data = [1,2,3]
data_numpy = np.array(data)
data_numpy

array([1, 2, 3])

In [14]:
# 3. 0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요.
data = np.arange(100)
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
# 4. 구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요.
data = np.arange(1,10) * 3
data

array([0, 3, 6, 9])

In [8]:
# 폴더 add
!git add Numpy.ipynb

In [9]:
# 커밋하기
!git commit -m 'Lets go 1st'
!git push

[main c7085c3] Lets go
 1 file changed, 1 insertion(+), 1 deletion(-)
 rewrite Numpy.ipynb (64%)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 596 bytes | 85.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/NUMCHCOMCH/Numpy.git
   8b201c5..c7085c3  main -> main
